# Required
Disease/Phenotype terms: renal, kidney, nephro, glomerul, distal tubule 
Output directory name: CKD

# Optional
Additional associated terms: 
Diseases/Phenotypes to exclude: adrenal
