# Required
Disease/Phenotype terms: epilep, seizure
Run name: Epilepsy

# Optional
Additional feature terms: nerve, brain, nervous, neuronal, cerebellum, cerebral, hippocampus, hypothalamus
Diseases/Phenotypes to exclude: 
Genes to highlight: 
