# Required
Disease/Phenotype terms: epilep, seizure
Output directory name: Epilepsy

# Optional
Additional associated terms: brain, nerve, nervous, neuronal, cerebellum, cerebral, hippocampus, hypothalamus
Diseases/Phenotypes to exclude: 
